name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches:
      - main
jobs:
  Windows:
    runs-on: windows-2022
    steps:
      - run: echo "OS - ${{ runner.os }}; Repository - ${{ github.repository }}; Branch - ${{ github.ref }}"
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: python --version
      - name: Install python packages
        run: python -m pip install -r requirements.txt
      - name: Execute python script
        run: python src/sample.py
      - name: Test with pytest
        run: |
          pytest --junitxml=junit/test-results.xml
      - name: Test summary
        uses: test-summary/action@v2
        with:
          paths: "junit/*.xml"
          # output: "tests/summary.md"
          show: "all"
        if: always()
      - name: Create package
        run: pyinstaller src/sample.py
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."

  Linux:
    runs-on: ubuntu-22.04
    steps:
      - run: echo "OS - ${{ runner.os }}; Repository - ${{ github.repository }}; Branch - ${{ github.ref }}"
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: python --version
      - name: Install python packages
        run: python -m pip install -r requirements.txt
      - name: Execute python script
        run: python src/sample.py
      - name: Create package
        run: pyinstaller src/sample.py
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
